Upload reports hint and automatically open reports file
RPMTW/launcher pull request #274
Opened 2022-08-12 14:42 UTC by BennyDioxide

Since too many newbies asking question about crash without sending crash reports, I made a hint and make it automatically opens the two crash reports.
The idea was originally by @YutaYamamoto212.

2022-08-14 10:46 UTC, SiongSng requested changes
Great feature, but some things need to be fixed

2022-08-14 10:46 UTC, SiongSng commented on lib/widget/dialog/GameCrash.dart
> +            Text(I18n.format("log.game.crash.info"),
The font is too big and looks weird

2022-08-14 10:46 UTC, SiongSng commented on lib/screen/Log.dart
> +        Util.openLatestCrashReport(instanceDir);
There should be a setting option to turn off auto open the crash report

2022-08-14 10:46 UTC, SiongSng commented on assets/lang/zh_tw.json
> +  "log.game.crash.info": "已自動開啟遊戲日誌及崩潰報告。\n請注意，退出代碼或錯誤訊息通常都不足以診斷問題！\n求助時，請一定要附上遊戲日誌及崩潰報告，以便診斷問題！",
中文翻譯可以先不用填寫，會在 Crowdin 上進行翻譯

2022-10-19 09:48 UTC, SiongSng commented
Good 我找時間 review

2022-12-18 11:48 UTC, BennyDioxide commented
因為接下來的重寫，加上我最近沒時間
因此將此PR關閉？

2022-12-20 09:33 UTC, SiongSng commented
OK

2022-12-20 09:33 UTC, closed without merging